language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
script: bundle exec rspec
before_install:
  - gem update --system
services:
  - redis-server
notifications:
  email: false
  webhooks:
    urls:
      - http://util.perceptes.com:8080/travis
